### ISSUE TITLE
"Invalid path: Invalid token in path" 

### ISSUE THREAD

**Issue by doczoidberg** [imranmomin/Hangfire.Firebase#5]
I get an error on:
```
RecurringJob.AddOrUpdate(
    () => Console.WriteLine("Recurring!"),
    Cron.Daily);
```

```Request responded with status code=BadRequest, response={ "error" : "Invalid path: Invalid token in path" } TRACE: at FireSharp.FirebaseClient.<>c.<.ctor>b__3_0(HttpStatusCode statusCode, String body) at FireSharp.FirebaseClient.HandleIfErrorResponse(HttpStatusCode statusCode, String content, Action`2 errorHandler) at FireSharp.FirebaseClient.Get(String path) at Hangfire.Firebase.FirebaseConnection.GetAllEntriesFromHash(String key) at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options) at Hangfire.RecurringJobManagerExtensions.AddOrUpdate(IRecurringJobManager manager, String recurringJobId, Job job, String cronExpression, TimeZoneInfo timeZone, String queue) at Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, String cronExpression, TimeZoneInfo timeZone, String queue) at Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, Func`1 cronExpression, TimeZoneInfo timeZone, String queue) at EO2.Controllers.Api2Controller.d__16.MoveNext()```

**Comment by imranmomin** [comment]
Can you remove the ! from the name. Maybe that causing the issue ?

Or

Can you check in Fiddler, and check the URL for what is casing the Bad Request? As there is nothing fancy inside `GetAllEntriesFromHash` method.

**Comment by doczoidberg** [comment]
which name?

Maybe my config is not right?

```
     GlobalConfiguration.Configuration.UseFirebaseStorage("my-firebase-8396.firebaseio.com", "flksajd faölsdkFDSFdshklfsdaakj");
     app.UseHangfireServer();
     app.UseHangfireDashboard();
```

I have also no access to the dashboard.

**Comment by imranmomin** [comment]
Your config is not correct.  Use the complete URL i.e. with https://
Also, are you using the correct key?. It should be the database secret from the project settings 

I hope you have configured the rules to setup the indexes.

**Comment by doczoidberg** [comment]
I have also tried with https:// and the right key.

I've also setup the rules.

**Comment by imranmomin** [comment]
I tried to reproduce it. But everything works fine for me.
Can you use [Fiddler](http://www.telerik.com/fiddler) and get the logs when it throws the exception. That might help

**Comment by doczoidberg** [comment]
I get no  useful information with fiddler.

I think I will use another technology.

**Comment by imranmomin** [comment]
No worries. We only need to find the URL / Payload which is causing the BadRequest for Firebase

**Comment by imranmomin** [comment]
if you could change the recurring job call, i.e assign a unique name to the job

`RecurringJob.AddOrUpdate("Job-name", () => Console.WriteLine("Recurring!"), Cron.Daily);`

You will need to add the name for the job, as Hangfire try to create a random unique name which includes some special character which are not allowed by Firebase to be part of the key.

**Comment by imranmomin** [comment]
Let me know if it helps to fix the issue.

**Comment by doczoidberg** [comment]
thanks for your reply but I use a python script instead.
