### ISSUE TITLE
Index not defined, add ".indexOn":"key" for path "sets" to the rules

### ISSUE THREAD

**Issue by mikerasky** [imranmomin/Hangfire.Firebase#7]
Hi Imran,

Good day!. I have tried the extension you made. It was great but unfortunately, it doesn't work on my end. Could you help me to solve this issue?

Exception Details: FireSharp.Exceptions.FirebaseException: Request responded with status code=BadRequest, response={
 "error" : "Index not defined, add \".indexOn\": \"key\", for path \"/sets\", to the rules"
}

This is my Configuration in MVC
            FirebaseStorageOptions firebaseOptions = new FirebaseStorageOptions
            {
                Queues = new[] { "default", "critical" },
                RequestTimeout = System.TimeSpan.FromSeconds(30),
                ExpirationCheckInterval = TimeSpan.FromMinutes(15),
                CountersAggregateInterval = TimeSpan.FromMinutes(1),
                QueuePollInterval = TimeSpan.FromSeconds(2)
            };

            FirebaseStorage firebaseStorage = new FirebaseStorage("https://sms-storage-aa2ca.firebaseio.com", "1pYbUgicyUlEfAS......................W5", firebaseOptions);
            GlobalConfiguration.Configuration.UseStorage(firebaseStorage);        

            app.UseHangfireDashboard();
            app.UseHangfireServer();

Firebase Rule:
{
	"rules": 
	{
		"hangfire":
		{
			"servers": 
			{
				".indexOn":["_id","server_id"]
			},
			"queue":
			{
				"default":
				{
					".indexOn": ["_id","server_id"]
				},
				"critical":
				{
					".indexOn": ["_id","server_id"]
				}
			},
			"jobs":
			{
				".indexOn":["_id","server_id","state_name"]
			},
			"sets":
      {
				".indexOn":["key"]
			},
			"lists":
			{
				".indexOn": ["key"]
			}
		},
		".read": "auth != null",
		".write": "auth != null"
	}
}

![hangfirefirebaseissue](https://user-images.githubusercontent.com/4996666/31816761-1b42abca-b5c4-11e7-819d-4c3c930922ae.jpg)

Regards,
Michael

**Comment by mikerasky** [comment]
I already solved my own issue. I just exclude this path "hangfire" on the rules. Thanks

Firebase Rule Setup

Under the Firebase database, please update the json so .indexOn is aviable for query. Note hangfire is the parent node. If you had additional queue, repeat the .indexOn for the queue.

**Comment by imranmomin** [comment]
Correct.. **Hangfire** is parent node. You can have any node as parent for hangfire documents.

**Comment by sbozzie** [comment]
Hia, I'm experiencing this error message and not sure how to "just exclude this path "hangfire" on the rules." as @mikerasky mentions above.
Is this a change that needs to be made to the database structure, C#, or the rules?

**Comment by imranmomin** [comment]
@sbozzie You will have to update the **rules** for the firebase database  

https://github.com/imranmomin/Hangfire.Firebase#firebase-rule-setup

**Comment by sbozzie** [comment]
![image](https://user-images.githubusercontent.com/4300375/41414394-bf4921da-6fdd-11e8-91dc-53d83ced78e7.png)

I have it set using that setup, but still get the same error

**Comment by imranmomin** [comment]
just to confirm is **hangfire** the parent node 

most likely the URL will be `"https://{account}.firebaseio.com/{parentnode}"`

**Comment by sbozzie** [comment]
Ah! Now I get it! Yes, I was not using the parent node in the URL.
Thank you for your help on this!
